const services={
"الصيانة":["صيانة كهربائية","صيانة الأنابيب ودورات المياه","أعمال الحدادة والنجارة","صيانة الأجهزة الإلكترونية","صيانة عمرانية"],
"الخدمات":["خدمات تنظيف","تجهيز","تعقيم","حدائق","واجهات مباني"],
"النقل والتجهيز":["نقل الكادر","نقل وتجهيز المواد","تأجير مركبات"],
"الضيافة والاستقبال":["تقديم الضيافة","إعداد الضيافة","استقبال","ريسبشن","كايد مواقع"],
"الأمن والباركينك":["أمن داخلي","أمن خارجي","أمن متنقل","باركينك عام","باركينك خاص"],
"الترويج والتسويق الإعلامي":["حملات ترويجية","إدارة منصات التواصل","تصوير ومحتوى","هوية وعلامة تجارية"],
"تكنولوجيا المعلومات":["دعم فني","شبكات وأنظمة","برمجيات وتطبيقات","أجهزة ومعدات"],"خدمات أخرى":[]};
const ADMIN_EMAIL='adil.maktob01@gmail.com';
const state={route:'start',history:[],service:null,category:null,form:null,clientType:null,location:null,requests:loadRequests(),adminTab:'new',filter:'',installPrompt:null};
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const icons={
"الصيانة":`<svg viewBox="0 0 64 64"><path d="M17 47l30-30M20 18l7 7M39 39l7 7M14 13c7-2 13 2 15 8l-8 8c-6-2-10-8-7-16zM50 51c-7 2-13-2-15-8l8-8c6 2 10 8 7 16z"/></svg>`,
"الخدمات":`<svg viewBox="0 0 64 64"><path d="M23 50h18M25 43h14M28 36h8M20 31c-5-7 0-17 8-17s13 10 8 17c-2 3-3 5-3 7H23c0-2-1-4-3-7z"/><path d="M46 19l5 5M50 14v5M55 19h-5"/></svg>`,
"النقل والتجهيز":`<svg viewBox="0 0 64 64"><path d="M9 19h33v25H9zM42 28h9l6 7v9H42zM17 50a5 5 0 1 0 0-10 5 5 0 0 0 0 10zM48 50a5 5 0 1 0 0-10 5 5 0 0 0 0 10zM14 25h18"/></svg>`,
"الضيافة والاستقبال":`<svg viewBox="0 0 64 64"><path d="M14 31h36v12H14zM19 25h26M20 43v7M44 43v7M11 31h42M24 19h16v6H24z"/></svg>`,
"الأمن والباركينك":`<svg viewBox="0 0 64 64"><path d="M32 8l20 7v15c0 13-9 22-20 26C21 52 12 43 12 30V15l20-7z"/><path d="M25 31h14M32 24v14"/></svg>`,
"الترويج والتسويق الإعلامي":`<svg viewBox="0 0 64 64"><path d="M11 27h18l23-12v34L29 37H11zM29 37l4 14H23l-4-14"/><path d="M54 24c3 3 3 13 0 16"/></svg>`,
"تكنولوجيا المعلومات":`<svg viewBox="0 0 64 64"><rect x="10" y="12" width="44" height="30" rx="3"/><path d="M24 52h16M32 42v10M22 24h20M22 31h13"/></svg>`,
"خدمات أخرى":`<svg viewBox="0 0 64 64"><circle cx="32" cy="32" r="22"/><path d="M22 32h20M32 22v20"/></svg>`};
function serviceIcon(n){return icons[n]||icons['خدمات أخرى']} function logo(){return `<img class="logo" src="assets/logo.png" alt="مكتوب">`}
function loadRequests(){try{return JSON.parse(localStorage.getItem('mak2b_requests')||'[]')}catch{return[]}} function save(){localStorage.setItem('mak2b_requests',JSON.stringify(state.requests));updateBadge()}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function updateBadge(){const b=$('#badge');if(!b)return;b.style.display=state.requests.some(r=>['قيد الانتظار','سعر جاهز'].includes(r.status))?'block':'none'}
function nav(route){if(state.route!==route)state.history.push(state.route);state.route=route;render()} function back(){state.route=state.history.pop()||'home';render()}
function card(title,sub,fn){return `<button class="card" onclick="${fn}"><div class="service-icon">${serviceIcon(title)}</div><strong>${esc(title)}</strong><small>${esc(sub)}</small></button>`}
function render(){updateBadge();$('#backBtn').style.visibility=['start','home'].includes(state.route)?'hidden':'visible';const c=$('#content');
if(state.route==='start')c.innerHTML=`<div class="hero">${logo()}<h1>ابدأ الآن</h1><p>اختر لغة التطبيق للمتابعة</p></div><div class="panel"><div class="lang-row"><button class="choice" onclick="nav('home')">العربية</button><button class="choice" onclick="nav('home')">English</button><button class="choice" onclick="nav('home')">کوردی</button></div></div>`;
else if(state.route==='home')renderHome();else if(state.route==='services')renderServices();else if(state.route.startsWith('cat:'))renderCategory(state.route.slice(4));else if(state.route==='form')renderForm();else if(state.route==='location')renderLocation();else if(state.route==='review')renderReview();else if(state.route==='sent')renderSent();else if(state.route==='my')renderMy();else if(state.route==='maktob')renderMaktob();else if(state.route==='company')renderCompany();else if(state.route==='adminLogin')renderAdminLogin();else if(state.route==='admin')renderAdmin();}
function renderHome(){const installed=!localStorage.getItem('mak2b_install_seen');$('#content').innerHTML=`<div class="hero">${logo()}<h1>مرحباً بك</h1><p>شريكك في النجاح بمستقبل مكتوب</p></div><div class="panel"><h2>كيف يمكننا خدمتك؟</h2><p>اختر نوع العميل للمتابعة.</p><div class="choice-row"><button class="choice" onclick="state.clientType='فرد';nav('services')">فرد</button><button class="choice" onclick="state.clientType='شركة';nav('company')">شركة</button></div></div>${installed?`<div class="panel install-panel"><h2>ثبّت مكتوب على هاتفك</h2><p>أضف التطبيق إلى الشاشة الرئيسية للوصول السريع والعمل بوضع التطبيق.</p><button class="gold-btn" onclick="installApp()">تثبيت التطبيق</button></div>`:''}`}
function renderServices(){$('#content').innerHTML=`<div class="hero"><h1>الأقسام الرئيسية</h1><p>اختر القسم الذي يلائم احتياجك.</p></div><div class="grid">${Object.keys(services).map(x=>card(x,x==='خدمات أخرى'?'اكتب حاجتك مباشرة':'استعرض خدمات القسم',`chooseCategory('${x}')`)).join('')}</div>`}
function chooseCategory(x){state.category=x;if(x==='خدمات أخرى'){state.service='خدمات أخرى';nav('form')}else nav('cat:'+x)}
function renderCategory(cat){$('#content').innerHTML=`<div class="hero"><div class="service-icon">${serviceIcon(cat)}</div><h1>${esc(cat)}</h1><p>اختر نوع الخدمة</p></div><div class="grid">${services[cat].map(x=>card(x,'طلب هذه الخدمة','chooseService(\''+x+'\')')).join('')}</div>`}
function chooseService(x){state.service=x;nav('form')}
function renderForm(){const title=state.service||'خدمات أخرى';$('#content').innerHTML=`<div class="panel"><h2>${esc(title)}</h2><p>أدخل التفاصيل التي تساعد القسم المختص على تقييم طلبك بدقة.</p><div class="field"><label>اسم العميل</label><input id="name" autocomplete="name" placeholder="الاسم الكامل"></div><div class="two"><div class="field"><label>عدد الكادر</label><input id="staff" type="number" min="0"></div><div class="field"><label>مدة العمل</label><input id="duration" placeholder="مثال: 3 أيام"></div></div><div class="two"><div class="field"><label>نوع الموقع</label><input id="site" placeholder="منزل، شركة، مجمع..."></div><div class="field"><label>عدد الطوابق</label><input id="floors" type="number" min="0"></div></div><div class="field"><label>المواد</label><select id="materials"><option>توفرها مكتوب</option><option>أوفرها أنا</option><option>حسب الاتفاق</option></select></div><div class="field"><label>شرح الحاجة</label><textarea id="note" placeholder="اكتب ما تحتاجه بالتفصيل..."></textarea></div><button class="gold-btn" onclick="toLocation()">متابعة وتحديد الموقع</button></div>`}
function toLocation(){const name=$('#name').value.trim();if(!name){toast('يرجى إدخال اسم العميل.');return}state.form={name,staff:$('#staff').value,duration:$('#duration').value,site:$('#site').value,floors:$('#floors').value,materials:$('#materials').value,note:$('#note').value};nav('location')}
function renderLocation(){$('#content').innerHTML=`<div class="panel"><h2>الموقع وبيانات التواصل</h2><div class="mapbox"><div><b>الموقع:</b> <span id="locText">لم يحدد بعد</span><br><small>يمكنك استخدام موقع الهاتف أو إدخال الإحداثيات.</small></div></div><div class="two" style="margin-top:10px"><button class="choice" onclick="useMyLocation()">موقعي الحالي</button><button class="choice" onclick="manualLocation()">إدخال الموقع</button></div><div class="field"><label>رقم الهاتف</label><input id="phone" inputmode="tel" autocomplete="tel" placeholder="07xxxxxxxxx"></div><div class="two"><div class="field"><label>خط العرض</label><input id="lat" inputmode="decimal" placeholder="اختياري"></div><div class="field"><label>خط الطول</label><input id="lng" inputmode="decimal" placeholder="اختياري"></div></div><label class="check"><input id="agree" type="checkbox"> أؤكد صحة المعلومات وألتزم بالحجز عند تأكيده، وأعلم أن تقديم معلومات غير صحيحة أو أي تحايل قد يعرّضني للمساءلة.</label><button class="gold-btn" onclick="toReview()">مراجعة الطلب</button></div>`}
function useMyLocation(){if(!navigator.geolocation){toast('المتصفح لا يدعم تحديد الموقع.');return}toast('جارٍ تحديد موقعك...');navigator.geolocation.getCurrentPosition(p=>{state.location={lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy};$('#lat').value=p.coords.latitude.toFixed(6);$('#lng').value=p.coords.longitude.toFixed(6);$('#locText').textContent='تم تحديد الموقع ✓';},()=>toast('تعذر الوصول إلى الموقع. فعّل صلاحية الموقع وحاول مرة أخرى.'),{enableHighAccuracy:true,timeout:10000,maximumAge:60000})}
function manualLocation(){const lat=prompt('أدخل خط العرض:');const lng=prompt('أدخل خط الطول:');if(lat&&lng){state.location={lat:Number(lat),lng:Number(lng),accuracy:null};$('#lat').value=lat;$('#lng').value=lng;$('#locText').textContent='تم إدخال الموقع ✓'}}
function toReview(){const phone=$('#phone').value.trim();if(!phone||!$('#agree').checked){toast('يرجى إدخال رقم الهاتف وتأكيد صحة المعلومات.');return}state.form.phone=phone;state.form.agree=true;state.location={lat:$('#lat').value||state.location?.lat||'',lng:$('#lng').value||state.location?.lng||'',accuracy:state.location?.accuracy||null};nav('review')}
function renderReview(){$('#content').innerHTML=`<div class="panel"><h2>مراجعة طلبك</h2><div class="status">راجع التفاصيل قبل الإرسال</div><div class="summary"><p><b>العميل:</b> ${esc(state.form.name)}</p><p><b>القسم:</b> ${esc(state.category||'خدمات أخرى')}</p><p><b>الخدمة:</b> ${esc(state.service||'خدمات أخرى')}</p><p><b>الهاتف:</b> ${esc(state.form.phone)}</p><p><b>الموقع:</b> ${state.location?.lat?esc(state.location.lat+', '+state.location.lng):'لم يحدد'}</p><p><b>التفاصيل:</b> ${esc(state.form.note||'—')}</p></div><div class="hero"><div id="timer" class="timer">10</div><p>ثوانٍ للمراجعة</p></div><button id="sendBtn" class="gold-btn" disabled>إرسال الطلب</button></div>`;let n=10;const t=setInterval(()=>{n--;if($('#timer'))$('#timer').textContent=n;if(n<=0){clearInterval(t);if($('#sendBtn')){$('#sendBtn').disabled=false;$('#sendBtn').onclick=sendRequest}}},1000)}
function sendRequest(){const id='MK-'+Date.now().toString(36).toUpperCase().slice(-8);state.requests.unshift({id,clientType:state.clientType||'فرد',client:state.form.name,service:state.service||'خدمات أخرى',category:state.category||'خدمات أخرى',phone:state.form.phone,form:{...state.form},location:{...state.location},status:'قيد الانتظار',price:'',adminNote:'',created:new Date().toLocaleString('ar-IQ'),customerDecision:'',updated:new Date().toISOString()});save();nav('sent')}
function renderSent(){$('#content').innerHTML=`<div class="hero">${logo()}<h1>تم إرسال طلبك</h1><p>رقم الطلب: <b>${esc(state.requests[0]?.id||'')}</b></p></div><div class="panel"><p>طلبك الآن قيد الانتظار. ستظهر لك قيمة الحجز وحالته داخل «خدمتي» بعد مراجعة الإدارة.</p><button class="gold-btn" onclick="nav('my')">متابعة طلباتي</button></div>`}
function renderMy(){const rs=state.requests;$('#content').innerHTML=`<div class="hero"><h1>خدمتي</h1><p>متابعة الحجوزات والأسعار والحالات.</p></div>${rs.length?rs.map((r,i)=>`<div class="req"><h3>${esc(r.service)}</h3><div class="meta">رقم الطلب: ${esc(r.id)}<br>العميل: ${esc(r.client)}<br>الحالة: ${esc(r.status)}<br>${r.price?`السعر: <b>${esc(r.price)}</b><br>`:''}${r.adminNote?`ملاحظة الإدارة: ${esc(r.adminNote)}<br>`:''}${esc(r.created)}</div>${r.status==='سعر جاهز'?`<div class="req-actions"><button class="gold-btn" onclick="customerDecision(${i},'تأكيد')">تأكيد الحجز</button><button class="outline-btn" onclick="customerDecision(${i},'رفض')">رفض</button></div>`:''}${r.status==='مؤكد'?`<div class="status ok">تم تأكيد الحجز</div>`:''}</div>`).join(''):`<div class="panel"><p>لا توجد طلبات حتى الآن.</p></div>`}`}
function customerDecision(i,d){const r=state.requests[i];r.customerDecision=d;r.status=d==='تأكيد'?'مؤكد':'مرفوض من العميل';r.updated=new Date().toISOString();save();toast(d==='تأكيد'?'تم تأكيد الحجز.':'تم رفض العرض.');render()}
function renderCompany(){$('#content').innerHTML=`<div class="hero">${logo()}<h1>خدمات الشركات</h1><p>حلول مصممة وفق احتياج مؤسستك.</p></div><div class="panel"><p><b>البريد:</b> adil.maktob01@gmail.com</p><p><b>Instagram:</b> Maak22b</p><div class="req-actions"><button class="gold-btn" onclick="location.href='mailto:${ADMIN_EMAIL}'">البريد الإلكتروني</button><button class="outline-btn" onclick="location.href='https://instagram.com/Maak22b'">Instagram</button></div></div>`}
function renderMaktob(){$('#content').innerHTML=`<div class="hero">${logo()}<h1>مكتوب</h1><p>الخدمات العامة والحلول المتكاملة</p></div><div class="panel"><h2>من نحن</h2><p>مختصون في تقديم الخدمات العامة والحلول المتكاملة للشركات والمؤسسات والمجمعات السكنية والتجارية، نعمل بروح الابتكار والالتزام لتوفير بيئة أكثر كفاءة واستقراراً.</p><h2>رؤيتنا</h2><p>بناء شراكات موثوقة وتقديم خدمات منظمة ومرنة.</p><h2>أهدافنا</h2><p>رفع جودة التنفيذ، تبسيط تجربة العميل، وتوفير حلول متكاملة.</p></div>`}
async function sha256(text){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function renderAdminLogin(){$('#content').innerHTML=`<div class="hero">${logo()}<h1>إدارة مكتوب</h1><p>منطقة الإدارة الخاصة بصاحب التطبيق.</p></div><div class="panel"><div class="field"><label>البريد الإلكتروني</label><input id="adminEmail" type="email" value="${ADMIN_EMAIL}"></div><div class="field"><label>كلمة المرور</label><input id="adminPass" type="password" placeholder="كلمة مرور الإدارة"></div><button class="gold-btn" onclick="adminLogin()">دخول الإدارة</button><p class="admin-note">في أول دخول، أنشئ كلمة مرور من 8 أحرف أو أكثر. هذه نسخة محلية؛ الربط السحابي يحتاج إعداد خادم.</p></div>`}
async function adminLogin(){const email=$('#adminEmail').value.trim().toLowerCase(),pass=$('#adminPass').value;if(email!==ADMIN_EMAIL){toast('البريد غير مصرح له.');return}if(pass.length<8){toast('كلمة المرور يجب أن تكون 8 أحرف على الأقل.');return}const hash=await sha256(pass),saved=localStorage.getItem('mak2b_admin_hash');if(!saved){localStorage.setItem('mak2b_admin_hash',hash);sessionStorage.setItem('mak2b_admin','1');toast('تم إنشاء حساب الإدارة محلياً.');nav('admin');return}if(hash!==saved){toast('بيانات الدخول غير صحيحة.');return}sessionStorage.setItem('mak2b_admin','1');nav('admin')}
function adminAuth(){if(sessionStorage.getItem('mak2b_admin')!=='1'){nav('adminLogin');return false}return true}
function renderAdmin(){if(!adminAuth())return;const counts={new:state.requests.filter(r=>r.status==='قيد الانتظار').length,price:state.requests.filter(r=>r.status==='سعر جاهز').length,active:state.requests.filter(r=>['مؤكد','قيد الإنجاز'].includes(r.status)).length,done:state.requests.filter(r=>r.status==='منجز').length,rejected:state.requests.filter(r=>r.status.includes('مرفوض')).length};let list=state.requests.filter(r=>satisfies(r,state.adminTab));if(state.filter)list=list.filter(r=>(r.id+' '+r.client+' '+r.phone+' '+r.service).toLowerCase().includes(state.filter.toLowerCase()));$('#content').innerHTML=`<div class="admin-shell"><div class="hero"><h1>لوحة الإدارة</h1><p>إدارة الطلبات والتسعير والتنفيذ.</p></div><div class="admin-grid"><div class="admin-stat"><strong>${counts.new}</strong><small>طلبات جديدة</small></div><div class="admin-stat"><strong>${counts.price}</strong><small>بانتظار قرار العميل</small></div><div class="admin-stat"><strong>${counts.active}</strong><small>مؤكدة / قيد الإنجاز</small></div><div class="admin-stat"><strong>${counts.done}</strong><small>منجزة</small></div></div><div class="field"><input value="${esc(state.filter)}" oninput="state.filter=this.value;render()" placeholder="بحث بالرقم أو الاسم أو الهاتف أو الخدمة"></div><div class="tabs">${[['new','الجديدة'],['price','الأسعار'],['active','النشطة'],['done','المنجزة'],['rejected','المرفوضة']].map(x=>'<button onclick="state.adminTab=\''+x[0]+'\';render()">'+x[1]+'</button>').join('')}</div>${list.length?list.map(r=>adminRequestCard(r)).join(''):`<div class="panel"><p>لا توجد طلبات.</p></div>`}<div class="req-actions"><button class="outline-btn" onclick="window.print()">طباعة الصفحة</button><button class="outline-btn" onclick="adminLogout()">خروج الإدارة</button></div></div>`}
function satisfies(r,t){return t==='new'?r.status==='قيد الانتظار':t==='price'?r.status==='سعر جاهز':t==='active'?['مؤكد','قيد الإنجاز'].includes(r.status):t==='done'?r.status==='منجز':t==='rejected'?r.status.includes('مرفوض'):true}
function adminRequestCard(r){return `<div class="req"><h3>${esc(r.service)} — ${esc(r.id)}</h3><div class="meta">العميل: ${esc(r.client)} (${esc(r.clientType)})<br>الهاتف: ${esc(r.phone)}<br>القسم: ${esc(r.category)}<br>تاريخ الطلب: ${esc(r.created)}<br>الكادر: ${esc(r.form.staff||'—')} | المدة: ${esc(r.form.duration||'—')}<br>الموقع: ${esc(r.form.site||'—')} | الطوابق: ${esc(r.form.floors||'—')}<br>المواد: ${esc(r.form.materials||'—')}<br>الشرح: ${esc(r.form.note||'—')}<br>الإحداثيات: ${r.location?.lat?esc(r.location.lat+', '+r.location.lng):'—'}<br>الحالة: <b>${esc(r.status)}</b>${r.price?`<br>السعر: <b>${esc(r.price)}</b>`:''}</div><div class="field"><label>ملاحظة للعميل</label><input id="note-${r.id}" value="${esc(r.adminNote||'')}" placeholder="ملاحظة اختيارية"></div>${r.status==='قيد الانتظار'?`<div class="price-row"><input id="price-${r.id}" placeholder="قيمة الحجز"><button class="gold-btn" onclick="setPrice('${r.id}')">إرسال السعر</button></div><div class="req-actions"><button class="outline-btn" onclick="saveAdminNote('${r.id}')">حفظ الملاحظة</button><button class="outline-btn" onclick="setAdminStatus('${r.id}','مرفوض من الإدارة')">رفض</button></div>`:r.status==='سعر جاهز'?`<div class="req-actions"><button class="outline-btn" onclick="saveAdminNote('${r.id}')">حفظ الملاحظة</button><button class="outline-btn" onclick="setAdminStatus('${r.id}','قيد الإنجاز')">بدء التنفيذ</button></div>`:r.status==='مؤكد'||r.status==='قيد الإنجاز'?`<div class="req-actions"><button class="outline-btn" onclick="saveAdminNote('${r.id}')">حفظ الملاحظة</button><button class="outline-btn" onclick="setAdminStatus('${r.id}','منجز')">تحديد كمنجز</button></div>`:`<div class="req-actions"><button class="outline-btn" onclick="printRequest('${r.id}')">طباعة / PDF</button></div>`}</div>`}
function setPrice(id){const r=state.requests.find(x=>x.id===id),v=$('#price-'+id)?.value.trim();if(!v){toast('أدخل قيمة الحجز.');return}r.price=v;r.status='سعر جاهز';r.updated=new Date().toISOString();save();toast('تم إرسال السعر إلى خدمتي.');render()}
function saveAdminNote(id){const r=state.requests.find(x=>x.id===id);r.adminNote=$('#note-'+id)?.value.trim()||'';r.updated=new Date().toISOString();save();toast('تم حفظ الملاحظة.');render()}
function setAdminStatus(id,status){const r=state.requests.find(x=>x.id===id);r.status=status;r.updated=new Date().toISOString();save();toast('تم تحديث حالة الطلب.');render()}
function printRequest(id){const r=state.requests.find(x=>x.id===id);if(!r)return;const rows=[['رقم الطلب',r.id],['العميل',r.client],['الهاتف',r.phone],['القسم',r.category],['الخدمة',r.service],['التاريخ',r.created],['عدد الكادر',r.form.staff],['مدة العمل',r.form.duration],['نوع الموقع',r.form.site],['الطوابق',r.form.floors],['المواد',r.form.materials],['الشرح',r.form.note],['الإحداثيات',r.location?.lat?`${r.location.lat}, ${r.location.lng}`:'—'],['السعر',r.price||'لم يحدد'],['الحالة',r.status],['ملاحظة الإدارة',r.adminNote||'—']];const w=window.open('','_blank');if(!w){toast('اسمح بالنوافذ المنبثقة للطباعة.');return}w.document.write(`<html dir="rtl"><head><title>${esc(r.id)}</title><style>body{font-family:Arial;padding:30px;line-height:2}h1{border-bottom:2px solid #b99442}table{width:100%;border-collapse:collapse}td{border:1px solid #aaa;padding:8px}td:first-child{font-weight:bold;width:30%}</style></head><body><h1>مكتوب — تفاصيل الطلب ${esc(r.id)}</h1><table>${rows.map(a=>`<tr><td>${esc(a[0])}</td><td>${esc(a[1])}</td></tr>`).join('')}</table><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}
function adminLogout(){sessionStorage.removeItem('mak2b_admin');nav('home')}
function installApp(){if(state.installPrompt){state.installPrompt.prompt();state.installPrompt.userChoice.then(()=>{state.installPrompt=null;localStorage.setItem('mak2b_install_seen','1')})}else toast('من قائمة المتصفح اختر «إضافة إلى الشاشة الرئيسية» أو «تثبيت التطبيق».')}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.installPrompt=e});window.addEventListener('appinstalled',()=>localStorage.setItem('mak2b_install_seen','1'));
$('#backBtn').onclick=back;$('#adminBtn').onclick=()=>nav('adminLogin');document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>nav(b.dataset.route));
let visits=Number(localStorage.getItem('mak2b_visits')||0)+1;localStorage.setItem('mak2b_visits',String(visits));if(!localStorage.getItem('mak2b_installs'))localStorage.setItem('mak2b_installs','0');setTimeout(()=>{$('#splash').classList.add('hidden');$('#app').classList.remove('hidden');render()},1400);
